version: "3"
services:
  postgres:
    container_name: postgresback
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mcoa_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcoa_dev
  backend:
    image: klak_backend
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    