version: "3.3"

services:
  frontend:
    container_name: klakin
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app